development:
  adapter: async

test:
  adapter: async

production:
  # adapter: redis
  # url: redis://h:p9kbl7oc5884t8db6vb5tdojrif@ec2-23-23-218-119.compute-1.amazonaws.com:20709
  url: redis://localhost:6379